# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [244]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [245]:
A = np.arange(1, 16).reshape(3,5)

In [246]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [247]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [248]:
print(B - C)

print(B * C)

print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [249]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [250]:
np.exp(B)
print (np.exp(B))

print(B.min())

print(B.min(axis=1))

print(B.min(axis=0))

print(np.argmin(B.min()))

print(np.argmin(B.min(axis=1)))

print(B.sum())

print(np.mean(B, axis=0))

print(np.median(B, axis=0))



[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
0
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [251]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [252]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

It means that the missing indices are considered complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [253]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [254]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


I would use the product operator *, to iterate through the array elementwise.

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [255]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


(np.arange(30)) koden gav oss 30 element.
a.reshape((2, 3, -1)) innebär att vi ska få ut 2 block där varje block består av 3 rader och -1 är som en "whatever is needed", alltså fixade den automatiskt att det skulle vara 5 kolumner.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [256]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [257]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [258]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [259]:
#10.1.1

#a) Vektorn x har dimension 2 då den har 2 komponenter.
x = np.array([4, 3])
print(x)
print(x * 5)
print(x * 3)
print((x*5) + (x*3))
print(x * 8)
print((x*4)-(x))

np.atleast_2d(x).T
print(np.atleast_2d(x).T)
# h) nej det är ej definierat då de är av olika dimensioner. 

np.linalg.norm(x)

[4 3]
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
[[4]
 [3]]


np.float64(5.0)

In [260]:
#10.1.2
#a) Vektorn v har dimension 4 då den har fyra komponenter. 
v = np.array([[3], [7], [0], [11]])
print(v)

print(2 * v)

print ((5 * v)+(2 * v))

print((4 * v)-(2 * v))

#e) Beräkna v^T
np.atleast_2d(v).T
print(np.atleast_2d(v).T)

#f) Beräkna ||v||
np.linalg.norm(v)



[[ 3]
 [ 7]
 [ 0]
 [11]]
[[ 6]
 [14]
 [ 0]
 [22]]
[[21]
 [49]
 [ 0]
 [77]]
[[ 6]
 [14]
 [ 0]
 [22]]
[[ 3  7  0 11]]


np.float64(13.379088160259652)

In [261]:
#10.1.3
#Beräkna ||v1|| 
v1 = np.array([4, 3, 1, 5])
print (v1)

v2 = np.array([2, 3, 1, 1])
print(v2)

#Beräkna ||v1 - v2||
w = np.linalg.norm(v1)
print(w)

z = np.linalg.norm(v2)
print(z)

print (w - z)



[4 3 1 5]
[2 3 1 1]
7.14142842854285
3.872983346207417
3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [262]:
#10.2.1

A = np.array ([[2, 1, -1],
               [1, -1, 1]])
print(A)

B = np.array([[4, -2, 1],
              [2, -4, -2]])
print(B)

C = np.array([[1, 2],
              [2, 1]])
print(C)

D = np.array([[3, 4],
              [4, 3]])
print(D)

E = np.array([[1],
              [2]])
print(E)

I = np.array([[1, 0], 
              [0, 1]])
print(I)


[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]
[[1 0]
 [0 1]]


In [263]:
print (A * 2)
print(B - (2 * A))
print((3 * C) - (2 * E))
print((2 * D) -(3 * C))

#e) D^T + 2D
D1 = np.atleast_2d(D).T
print(D1)
print(D * 2)
print(D1 + (D * 2))


[[ 4  2 -2]
 [ 2 -2  2]]
[[ 0 -4  3]
 [ 0 -2 -4]]
[[ 1  4]
 [ 2 -1]]
[[3 2]
 [2 3]]
[[3 4]
 [4 3]]
[[6 8]
 [8 6]]
[[ 9 12]
 [12  9]]


In [264]:
#f) 2C^T - 2D^T
CT = np.atleast_2d(C).T
print (CT)
print((CT * 2))

DT = np.atleast_2d(D).T
print(DT)
print(DT * 2)

print((CT * 2) - (DT * 2))

[[1 2]
 [2 1]]
[[2 4]
 [4 2]]
[[3 4]
 [4 3]]
[[6 8]
 [8 6]]
[[-4 -4]
 [-4 -4]]


In [265]:
#g) A^T - B
AT = np.atleast_2d(A).T
print(AT)
print(B)

result_subtraction = AT - B
print(result_subtraction)


#Ej definierat 


[[ 2  1]
 [ 1 -1]
 [-1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [209]:
# h) AC
result15 = np.dot(A, C)
print(result15)


[[ 5  4]
 [10  8]]


In [207]:
#i) CD
result14 = np.dot(C, D)
print(result14)


[[11 10]
 [10 11]]


In [205]:
#j) CB

result13 = np.dot(C, B)
print(result13)


[[  8 -10  -3]
 [ 10  -8   0]]


In [206]:
#k) CI

result12 = np.dot(C, I)
print(result12)


[[1 2]
 [2 1]]


In [203]:
#l) AB^T
print(A)
BT = print(np.atleast_2d(B).T)
print(BT)

result11 = np.dot(A, BT)
print(result11)

#Ej definierat



[[1, 2], [2, 4]]
[[ 4  2]
 [-2 -4]
 [ 1 -2]]
None


TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [202]:
#10.2.2
#Beräkna AA^T
Amat = np.array([[2, 3, 4], 
                [5, 4, 1]])

print(Amat)

AT2 = print(np.atleast_2d(Amat).T)
print(AT2)

result10 = np.dot(Amat, AT2)
print(result10)

#Ej definierat

[[2 3 4]
 [5 4 1]]
[[2 5]
 [3 4]
 [4 1]]
None


TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [201]:
#10.2.3

import numpy as np

A3 = np.array([[1, 2],
               [2, 4]])
print(A3)

B3 = np.array([[2, 1],
               [1, 3]])
print(B3)

C3 = np.array([[4, 3],
               [0, 2]])
print(C3)

result1 = np.dot(A3, B3)
print(result1)

result2 = np.dot(A3, C3)
print(result2)

[[1 2]
 [2 4]]
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]
[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [27]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [28]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [29]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
